name: kas_mini_lite
description: "Lariskas Lite - Aplikasi Kasir untuk UKM berbasis Flutter"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^3.3.8
  barcode: ^2.2.9
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  device_info_plus: ^10.0.1
  dio: ^5.8.0+1
  esc_pos_utils_plus: ^2.0.4
  excel: ^2.0.5
  file_picker: ^10.1.2
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.4.0
  flutter_file_dialog: ^3.0.2
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.11
  font_awesome_flutter: ^10.8.0
  gallery_saver_plus: ^3.2.4
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.3.0
  iconify_flutter: ^0.0.7
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decode: ^0.3.1
  liquid_pull_to_refresh: ^3.0.1
  logger: ^2.5.0
  lottie: 3.2.0
  media_scanner: ^2.2.0
  multipart: ^0.1.2
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pinput: ^5.0.1
  provider: ^6.1.2
  pull_to_refresh_flutter3: ^2.0.2
  qr_code_scanner_plus: ^2.0.6
  quickalert: ^1.1.0
  receipt_generator: ^0.0.5
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  simple_animations: ^5.1.0
  sizer: ^3.0.5
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5+4
  syncfusion_flutter_charts: ^28.2.11
  toast: ^0.3.0
  toastification: ^2.3.0
  uuid: ^4.3.3
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this: Image.assets('assets/images/logo-outlined.png')
  # it's auto included after /images/...
  assets:
    - assets/images/
    - assets/products/
    - assets/profiles/
    - assets/qr/
    - assets/qr/barcode.png
    - assets/qr/barcodeNama.png
    - assets/qr/barcodeHarga.png
    - assets/qr/barcodeHargaNama.png
    - assets/qr/qrcode.png
    - assets/qr/qrcodeNama.png
    - assets/qr/qrcodeHarga.png
    - assets/qr/qrcodeHargaNama.png
    - assets/lottie/
    - assets/sounds/
    - assets/sounds/success.wav
    - assets/images/Plus.png
    - assets/images/minus.png
    - assets/images/Logo-Kasmini.jpg
